import { useState } from 'react';
import { expenseAPI } from '../../utils/api';
import { formatCurrency, formatDate, Spinner } from '../ui/index.jsx';
import toast from 'react-hot-toast';

const CATEGORY_ICONS = { food:'🍽️', transport:'🚗', stay:'🏨', activity:'🎯', shopping:'🛍️', other:'📌' };

export default function TripReport({ tripId, trip }) {
  const [report, setReport] = useState(null);
  const [loading, setLoading] = useState(false);

  async function loadReport() {
    setLoading(true);
    try {
      const data = await expenseAPI.report(tripId);
      setReport(data);
    } catch (err) {
      toast.error('Failed to generate report');
    } finally {
      setLoading(false);
    }
  }

  function downloadReport() {
    if (!report) return;
    const lines = [
      `NAM PAYANAM - TRIP REPORT`,
      `நம் பயணம்`,
      `═══════════════════════════════`,
      ``,
      `Trip: ${report.trip?.title}`,
      `Route: ${report.trip?.start_location} → ${report.trip?.end_location}`,
      `Dates: ${formatDate(report.trip?.start_date)} to ${formatDate(report.trip?.end_date)}`,
      `Group Size: ${report.members?.length} members`,
      `Generated: ${new Date(report.generatedAt).toLocaleString()}`,
      ``,
      `═══════════════════════════════`,
      `EXPENSE SUMMARY`,
      `═══════════════════════════════`,
      `Total Spent: ${formatCurrency(report.totalAmount)}`,
      `Per Person Average: ${formatCurrency(report.perPersonAverage)}`,
      ``,
      `CATEGORY BREAKDOWN`,
      ...Object.entries(report.categoryBreakdown || {}).map(([cat, amt]) =>
        `  ${CATEGORY_ICONS[cat]} ${cat.toUpperCase()}: ${formatCurrency(amt)}`),
      ``,
      `═══════════════════════════════`,
      `PER MEMBER BREAKDOWN`,
      `═══════════════════════════════`,
      ...(report.memberBreakdown || []).map(m =>
        `${m.nickname}${m.isOrganizer ? ' (Organizer)' : ''}\n  Paid: ${formatCurrency(m.totalPaid)} | Share: ${formatCurrency(m.totalShare)}`),
      ``,
      `═══════════════════════════════`,
      `DAY-WISE EXPENSES`,
      `═══════════════════════════════`,
      ...(report.dayExpenses || []).flatMap(day => [
        ``,
        `Day ${day.dayNumber}: ${day.title}`,
        `  Total: ${formatCurrency(day.dayTotal)}`,
        ...day.expenses.map(e => `  • ${e.title}: ${formatCurrency(e.amount)} (paid by ${e.paid_by_nickname})`),
      ]),
      ``,
      `═══════════════════════════════`,
      `Generated by Nam Payanam (நம் பயணம்)`,
      `Your comprehensive trip planning friend`,
    ];

    const blob = new Blob([lines.join('\n')], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `NamPayanam-${trip?.title?.replace(/\s+/g,'-') || 'trip'}-report.txt`;
    a.click();
    URL.revokeObjectURL(url);
    toast.success('Report downloaded! 📄');
  }

  if (!report && !loading) {
    return (
      <div className="px-4 py-12 text-center">
        <div className="text-5xl mb-4">📊</div>
        <h3 className="font-display font-bold text-slate-800 text-lg mb-2">Trip Report</h3>
        <p className="text-sm text-slate-500 mb-6">Generate a complete breakdown of your trip — expenses per person, day-wise costs, and more.</p>
        <button onClick={loadReport} className="btn-primary px-8 flex items-center gap-2 mx-auto">
          📊 Generate Report
        </button>
      </div>
    );
  }

  if (loading) return (
    <div className="flex flex-col items-center justify-center py-16 gap-3">
      <Spinner size="lg" />
      <p className="text-sm text-slate-500">Generating your trip report...</p>
    </div>
  );

  return (
    <div className="px-4 py-4 space-y-4 pb-12 animate-fade-in">
      {/* Header */}
      <div className="card p-5 bg-gradient-to-br from-saffron-500 to-orange-600 text-white">
        <div className="flex items-start justify-between mb-3">
          <div>
            <h2 className="font-display font-bold text-xl">{report.trip?.title}</h2>
            <p className="text-white/70 text-xs mt-1">{report.trip?.start_location} → {report.trip?.end_location}</p>
          </div>
          <span className="text-3xl">📊</span>
        </div>
        <div className="grid grid-cols-3 gap-3 mt-4">
          <div className="bg-white/20 rounded-xl p-2.5 text-center">
            <div className="font-display font-bold text-xl">{formatCurrency(report.totalAmount)}</div>
            <div className="text-white/70 text-[10px] mt-0.5">Total Spent</div>
          </div>
          <div className="bg-white/20 rounded-xl p-2.5 text-center">
            <div className="font-display font-bold text-xl">{formatCurrency(report.perPersonAverage)}</div>
            <div className="text-white/70 text-[10px] mt-0.5">Per Person</div>
          </div>
          <div className="bg-white/20 rounded-xl p-2.5 text-center">
            <div className="font-display font-bold text-xl">{report.members?.length}</div>
            <div className="text-white/70 text-[10px] mt-0.5">Members</div>
          </div>
        </div>
      </div>

      {/* Category breakdown */}
      {Object.keys(report.categoryBreakdown || {}).length > 0 && (
        <div className="card p-4">
          <h3 className="font-display font-bold text-slate-700 mb-3">By Category</h3>
          <div className="space-y-2">
            {Object.entries(report.categoryBreakdown).sort(([,a],[,b]) => b-a).map(([cat, amt]) => {
              const pct = Math.round((amt / report.totalAmount) * 100);
              return (
                <div key={cat}>
                  <div className="flex items-center justify-between text-sm mb-1">
                    <span className="flex items-center gap-1.5 font-semibold text-slate-700">
                      {CATEGORY_ICONS[cat]} {cat.charAt(0).toUpperCase() + cat.slice(1)}
                    </span>
                    <span className="text-slate-600 font-bold">{formatCurrency(amt)} <span className="text-slate-400 font-normal text-xs">({pct}%)</span></span>
                  </div>
                  <div className="h-1.5 bg-slate-100 rounded-full overflow-hidden">
                    <div className="h-full bg-saffron-400 rounded-full" style={{ width: `${pct}%` }} />
                  </div>
                </div>
              );
            })}
          </div>
        </div>
      )}

      {/* Member breakdown */}
      <div className="card p-4">
        <h3 className="font-display font-bold text-slate-700 mb-3">Per Member</h3>
        <div className="space-y-2">
          {report.memberBreakdown?.map((m, i) => (
            <div key={i} className="bg-slate-50 rounded-xl p-3">
              <div className="flex items-center justify-between mb-1.5">
                <span className="font-semibold text-slate-800 text-sm">
                  {m.nickname} {m.isOrganizer && <span className="text-[10px] text-saffron-600">★ Organizer</span>}
                </span>
              </div>
              <div className="grid grid-cols-2 gap-2">
                <div>
                  <span className="text-[10px] text-slate-400 block">Total Paid</span>
                  <span className="text-sm font-bold text-green-600">{formatCurrency(m.totalPaid)}</span>
                </div>
                <div>
                  <span className="text-[10px] text-slate-400 block">Their Share</span>
                  <span className="text-sm font-bold text-slate-700">{formatCurrency(m.totalShare)}</span>
                </div>
              </div>
            </div>
          ))}
        </div>
      </div>

      {/* Day-wise */}
      <div className="card p-4">
        <h3 className="font-display font-bold text-slate-700 mb-3">Day-wise Expenses</h3>
        <div className="space-y-3">
          {report.dayExpenses?.filter(d => d.expenses.length > 0).map((day, i) => (
            <div key={i} className="bg-slate-50 rounded-xl p-3">
              <div className="flex items-center justify-between mb-2">
                <span className="font-semibold text-slate-700 text-sm">Day {day.dayNumber}: {day.title}</span>
                <span className="font-bold text-saffron-600 text-sm">{formatCurrency(day.dayTotal)}</span>
              </div>
              {day.expenses.map((exp, j) => (
                <div key={j} className="flex items-center justify-between py-1 border-t border-slate-200 first:border-0">
                  <span className="text-xs text-slate-600">{CATEGORY_ICONS[exp.category]} {exp.title}</span>
                  <span className="text-xs font-semibold text-slate-700">{formatCurrency(exp.amount)}</span>
                </div>
              ))}
            </div>
          ))}
        </div>
      </div>

      {/* Download */}
      <button onClick={downloadReport} className="btn-ocean w-full flex items-center justify-center gap-2 py-4">
        📥 Download Full Report
      </button>

      <p className="text-xs text-slate-400 text-center pb-4">
        Share this report to help others plan similar trips! 🗺️
      </p>
    </div>
  );
}
