import { useState } from 'react';
import { expenseAPI } from '../../utils/api';
import { formatCurrency, formatDate, Spinner } from '../ui/index.jsx';
import toast from 'react-hot-toast';

const CAT_ICONS = { food:'🍽️',transport:'🚗',stay:'🏨',activity:'🎯',shopping:'🛍️',fuel:'⛽',medical:'💊',other:'📌' };

export default function TripReport({ tripId, trip }) {
  const [report, setReport] = useState(null);
  const [loading, setLoading] = useState(false);

  async function load() {
    setLoading(true);
    try { const d=await expenseAPI.report(tripId); setReport(d); }
    catch { toast.error('Failed to generate report'); }
    finally { setLoading(false); }
  }

  function download() {
    if (!report) return;
    const lines = [
      `NAM PAYANAM — TRIP REPORT`,`நம் பயணம்`,`${'═'.repeat(40)}`,``,
      `Trip: ${report.trip?.title}`,
      `Route: ${report.trip?.start_location} → ${report.trip?.end_location}`,
      `Dates: ${formatDate(report.trip?.start_date)} to ${formatDate(report.trip?.end_date)}`,
      `Group: ${report.members?.length} members`,
      `Total Distance: ${report.totalDistanceKm||'N/A'} km`,
      `Generated: ${new Date().toLocaleString()}`,``,`${'═'.repeat(40)}`,
      `FINANCIAL SUMMARY`,`${'═'.repeat(40)}`,
      `Total Spent: ${formatCurrency(report.totalAmount)}`,
      `Per Person Average: ${formatCurrency(report.perPersonAverage)}`,``,
      `CATEGORY BREAKDOWN`,
      ...Object.entries(report.categoryBreakdown||{}).map(([c,a])=>`  ${CAT_ICONS[c]||'•'} ${c.toUpperCase()}: ${formatCurrency(a)}`),``,
      `${'═'.repeat(40)}`,`PER MEMBER BREAKDOWN`,`${'═'.repeat(40)}`,
      ...(report.memberBreakdown||[]).map(m=>`${m.nickname}${m.isOrganizer?' (Organiser)':''}\n  Paid: ${formatCurrency(m.totalPaid)} | Share: ${formatCurrency(m.totalShare)}`),``,
      `${'═'.repeat(40)}`,`DAY-WISE EXPENSES`,`${'═'.repeat(40)}`,
      ...(report.dayExpenses||[]).filter(d=>d.expenses.length>0).flatMap(day=>[
        ``,`Day ${day.dayNumber}: ${day.title}`,`  Total: ${formatCurrency(day.dayTotal)}`,
        ...day.expenses.map(e=>`  • ${e.title}: ${formatCurrency(e.amount)} (by ${e.paid_by_nickname})`),
      ]),``,
      `${'═'.repeat(40)}`,`BREAKS & STOPS`,`${'═'.repeat(40)}`,
      `Total Breaks: ${report.totalBreaks}`,``,
      `Generated by Nam Payanam (நம் பயணம்)`,
    ];
    const blob=new Blob([lines.join('\n')],{type:'text/plain'});
    const url=URL.createObjectURL(blob);
    const a=document.createElement('a');
    a.href=url; a.download=`NamPayanam-${trip?.title?.replace(/\s+/g,'-')}-report.txt`; a.click();
    URL.revokeObjectURL(url);
    toast.success('Report downloaded 📥');
  }

  if (!report && !loading) return (
    <div className="px-4 py-12 text-center">
      <div className="text-5xl mb-4">📊</div>
      <h3 className="font-display font-bold text-slate-800 text-lg mb-2">Trip Report</h3>
      <p className="text-sm text-slate-500 mb-6 max-w-xs mx-auto">Full breakdown of expenses, per-person costs, and places visited.</p>
      <button onClick={load} className="btn-primary px-8 mx-auto">📊 Generate Report</button>
    </div>
  );

  if (loading) return <div className="flex flex-col items-center justify-center py-16 gap-3"><Spinner size="lg" color="indigo"/><p className="text-sm text-slate-500">Generating report...</p></div>;

  return (
    <div className="px-4 py-4 space-y-4 pb-12 animate-fade-in">
      {/* Hero */}
      <div className="card-indigo rounded-2xl p-5">
        <div className="flex items-start justify-between mb-4">
          <div><h2 className="font-display font-bold text-white text-xl">{report.trip?.title}</h2>
            <p className="text-white/60 text-xs mt-1">{report.trip?.start_location} → {report.trip?.end_location}</p></div>
          <span className="text-4xl">📊</span>
        </div>
        <div className="grid grid-cols-3 gap-2">
          {[{l:'Total',v:formatCurrency(report.totalAmount)},{l:'Per Person',v:formatCurrency(report.perPersonAverage)},{l:'Members',v:report.members?.length}].map(({l,v})=>(
            <div key={l} className="bg-white/15 rounded-xl p-2.5 text-center">
              <div className="font-display font-black text-saffron-400 text-lg">{v}</div>
              <div className="text-white/60 text-[10px]">{l}</div>
            </div>
          ))}
        </div>
      </div>

      {/* Category chart */}
      {Object.keys(report.categoryBreakdown||{}).length>0 && (
        <div className="card p-4">
          <h3 className="font-display font-bold text-slate-700 mb-3">By Category</h3>
          {Object.entries(report.categoryBreakdown).sort(([,a],[,b])=>b-a).map(([cat,amt])=>{
            const pct=Math.round((amt/report.totalAmount)*100);
            return (
              <div key={cat} className="mb-2.5">
                <div className="flex justify-between text-sm mb-1">
                  <span className="flex items-center gap-1.5 font-bold text-slate-700">{CAT_ICONS[cat]||'•'} {cat.charAt(0).toUpperCase()+cat.slice(1)}</span>
                  <span className="font-black text-slate-700">{formatCurrency(amt)}<span className="text-slate-400 font-normal text-xs ml-1">({pct}%)</span></span>
                </div>
                <div className="h-2 bg-slate-100 rounded-full overflow-hidden">
                  <div className="h-full bg-saffron-gradient rounded-full" style={{width:`${pct}%`}}/>
                </div>
              </div>
            );
          })}
        </div>
      )}

      {/* Member breakdown */}
      <div className="card p-4">
        <h3 className="font-display font-bold text-slate-700 mb-3">Per Member</h3>
        {report.memberBreakdown?.map((m,i)=>(
          <div key={i} className="bg-slate-50 rounded-xl p-3 mb-2">
            <div className="flex justify-between items-center mb-1.5">
              <span className="font-bold text-slate-800 text-sm">{m.nickname}{m.isOrganizer&&<span className="text-saffron-500 ml-1 text-xs">★</span>}</span>
            </div>
            <div className="grid grid-cols-2 gap-2">
              <div><span className="text-[10px] text-slate-400 block font-bold uppercase">Paid</span>
                <span className="text-sm font-black text-emerald-600">{formatCurrency(m.totalPaid)}</span></div>
              <div><span className="text-[10px] text-slate-400 block font-bold uppercase">Share</span>
                <span className="text-sm font-black text-slate-700">{formatCurrency(m.totalShare)}</span></div>
            </div>
          </div>
        ))}
      </div>

      {/* Day-wise */}
      <div className="card p-4">
        <h3 className="font-display font-bold text-slate-700 mb-3">Day-wise</h3>
        {report.dayExpenses?.filter(d=>d.expenses.length>0).map((day,i)=>(
          <div key={i} className="bg-slate-50 rounded-xl p-3 mb-2">
            <div className="flex justify-between mb-2">
              <span className="font-bold text-slate-700 text-sm">Day {day.dayNumber}: {day.title}</span>
              <span className="font-black text-saffron-600 text-sm">{formatCurrency(day.dayTotal)}</span>
            </div>
            {day.expenses.map((e,j)=>(
              <div key={j} className="flex justify-between py-1 border-t border-slate-100 first:border-0">
                <span className="text-xs text-slate-600">{CAT_ICONS[e.category]||'•'} {e.title}</span>
                <span className="text-xs font-black text-slate-700">{formatCurrency(e.amount)}</span>
              </div>
            ))}
          </div>
        ))}
      </div>

      <button onClick={download} className="btn-indigo w-full py-4">📥 Download Full Report</button>
      <p className="text-xs text-slate-400 text-center pb-4">Share this report to help others plan similar trips!</p>
    </div>
  );
}
